### ISSUE TITLE
missing space before = operator

### ISSUE THREAD

**Issue by rugbymauri** [whatwedo/PhpCodingStandard#5]
ECS doesn't complain about missing space before `=` Operator

```
        $exportNewsPost->abstract= $newsPost->getAbstract();
        $exportNewsPost->color= $newsPost->getColor();
```

**Comment by marcwieland95** [comment]
Jep. I can confirm that. Also with normal variables assigned it's not failing

**Comment by tuxes3** [comment]
![image](https://github.com/whatwedo/PhpCodingStandard/assets/5341293/3f7d706f-9e75-424f-b8c2-2e7d974b09df)

String `concat` should always be handled the same. Current ECS does not care about `$foo . 'asdf'.$bar`

**Comment by tuxes3** [comment]
`BinaryOperatorSpacesFixer` activated.
